const array = [
	"All",
	"Alexa Skills",
	"Amazon Devices",
	"Amazon Fashion",
	"Amazon Fresh",
	"Amazon Pharmacy",
	"Appliances",
	"App & Games",
	"Baby",
	"Beauty",
	"Books",
	"Car & Motorbike",
	"Clothing & Accesories",
	"Collectibles",
	"Computer & Accessories",
	"Deals",
	"Electronics",
	"Furniture",
	"Garden & Outdoors",
	"Gift Cards",
	"Grocery & Garment Foods",
];
export default array;
